2025-04-08 20:28:46,489 INFO    MainThread:24616 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2025-04-08 20:28:46,489 INFO    MainThread:24616 [wandb_setup.py:_flush():79] Configure stats pid to 24616
2025-04-08 20:28:46,489 INFO    MainThread:24616 [wandb_setup.py:_flush():79] Loading settings from C:\Users\Hao\.config\wandb\settings
2025-04-08 20:28:46,489 INFO    MainThread:24616 [wandb_setup.py:_flush():79] Loading settings from C:\Users\Hao\Downloads\LLM\Reasoning\wandb\settings
2025-04-08 20:28:46,490 INFO    MainThread:24616 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2025-04-08 20:28:46,490 INFO    MainThread:24616 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2025-04-08 20:28:46,490 INFO    MainThread:24616 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2025-04-08 20:28:46,490 INFO    MainThread:24616 [wandb_setup.py:_flush():79] Applying login settings: {}
2025-04-08 20:28:46,490 INFO    MainThread:24616 [wandb_init.py:_log_setup():533] Logging user logs to C:\Users\Hao\Downloads\LLM\Reasoning\wandb\run-20250408_202846-j7gt3w11\logs\debug.log
2025-04-08 20:28:46,490 INFO    MainThread:24616 [wandb_init.py:_log_setup():534] Logging internal logs to C:\Users\Hao\Downloads\LLM\Reasoning\wandb\run-20250408_202846-j7gt3w11\logs\debug-internal.log
2025-04-08 20:28:46,490 INFO    MainThread:24616 [wandb_init.py:_jupyter_setup():479] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002703EF7D100>
2025-04-08 20:28:46,490 INFO    MainThread:24616 [wandb_init.py:init():619] calling init triggers
2025-04-08 20:28:46,492 INFO    MainThread:24616 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'_fields': {'vocab_size': 16, 'device': 'cuda', 'work_dir': 'results', 'batch_size': 64, 'test_size': 4096, 'task': max_seq_len: 83
max_variables: 12
, 'model': activation: &id001 !!python/tuple
- true
- true
- true
bias: false
dropout: 0.1
emb_dim: 64
ff_dim: 128
flash: true
layer_norm: true
mlp: *id001
mlp_bias: true
num_heads: !!python/tuple
- 1
- 1
- 1
num_layers: 3
pos_enc: rotary
pos_max_len: 83
, 'training': eval_iter: 150
freeze_out: false
freeze_value: false
get_attn: 1000
get_checkpoints: 500
identity_query: false
label_smoothing: 0
lr: 0.0005
optimizer: adamw
pad_ignore: true
schedule: triangle
total_steps: 60000
warmup_steps: 20000
weight_decay: 0.01
, 'wandb': project: Reasoning
}, '_locked': False, '_type_safe': True, '_convert_dict': True, '_allow_dotted_keys': False, '_sort_keys': True}
2025-04-08 20:28:46,492 INFO    MainThread:24616 [wandb_init.py:init():669] starting backend
2025-04-08 20:28:46,492 INFO    MainThread:24616 [wandb_init.py:init():673] sending inform_init request
2025-04-08 20:28:46,493 INFO    MainThread:24616 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2025-04-08 20:28:46,494 INFO    MainThread:24616 [wandb_init.py:init():686] backend started and connected
2025-04-08 20:28:46,501 INFO    MainThread:24616 [wandb_run.py:_label_probe_notebook():1339] probe notebook
2025-04-08 20:28:46,501 INFO    MainThread:24616 [wandb_run.py:_label_probe_notebook():1349] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-04-08 20:28:46,502 INFO    MainThread:24616 [wandb_init.py:init():781] updated telemetry
2025-04-08 20:28:46,526 INFO    MainThread:24616 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2025-04-08 20:28:47,049 INFO    MainThread:24616 [wandb_init.py:init():867] starting run threads in backend
2025-04-08 20:28:47,658 INFO    MainThread:24616 [wandb_run.py:_console_start():2456] atexit reg
2025-04-08 20:28:47,659 INFO    MainThread:24616 [wandb_run.py:_redirect():2305] redirect: wrap_raw
2025-04-08 20:28:47,659 INFO    MainThread:24616 [wandb_run.py:_redirect():2370] Wrapping output streams.
2025-04-08 20:28:47,659 INFO    MainThread:24616 [wandb_run.py:_redirect():2395] Redirects installed.
2025-04-08 20:28:47,660 INFO    MainThread:24616 [wandb_init.py:init():911] run started, returning control to user process
2025-04-08 20:30:33,728 INFO    MainThread:24616 [jupyter.py:save_ipynb():387] not saving jupyter notebook
2025-04-08 20:30:33,728 INFO    MainThread:24616 [wandb_init.py:_pause_backend():444] pausing backend
2025-04-08 20:34:11,271 INFO    MainThread:24616 [wandb_init.py:_resume_backend():449] resuming backend
2025-04-08 20:34:11,274 INFO    MainThread:24616 [jupyter.py:save_ipynb():387] not saving jupyter notebook
2025-04-08 20:34:11,274 INFO    MainThread:24616 [wandb_init.py:_pause_backend():444] pausing backend
2025-04-08 20:34:16,258 INFO    MainThread:24616 [wandb_init.py:_resume_backend():449] resuming backend
2025-04-08 20:34:16,447 INFO    MainThread:24616 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2025-04-08 20:34:16,448 INFO    MainThread:24616 [wandb_setup.py:_flush():79] Configure stats pid to 24616
2025-04-08 20:34:16,448 INFO    MainThread:24616 [wandb_setup.py:_flush():79] Loading settings from C:\Users\Hao\.config\wandb\settings
2025-04-08 20:34:16,448 INFO    MainThread:24616 [wandb_setup.py:_flush():79] Loading settings from C:\Users\Hao\Downloads\LLM\Reasoning\wandb\settings
2025-04-08 20:34:16,448 INFO    MainThread:24616 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2025-04-08 20:34:16,448 INFO    MainThread:24616 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2025-04-08 20:34:16,448 INFO    MainThread:24616 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2025-04-08 20:34:16,448 INFO    MainThread:24616 [wandb_setup.py:_flush():79] Applying login settings: {}
2025-04-08 20:34:16,448 INFO    MainThread:24616 [wandb_init.py:_log_setup():533] Logging user logs to C:\Users\Hao\Downloads\LLM\Reasoning\wandb\run-20250408_203416-u7dx8q4s\logs\debug.log
2025-04-08 20:34:16,448 INFO    MainThread:24616 [wandb_init.py:_log_setup():534] Logging internal logs to C:\Users\Hao\Downloads\LLM\Reasoning\wandb\run-20250408_203416-u7dx8q4s\logs\debug-internal.log
2025-04-08 20:34:16,448 INFO    MainThread:24616 [wandb_init.py:init():619] calling init triggers
2025-04-08 20:34:16,450 INFO    MainThread:24616 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'_fields': {'vocab_size': 16, 'device': 'cuda', 'work_dir': 'results', 'batch_size': 64, 'test_size': 4096, 'task': max_seq_len: 83
max_variables: 12
, 'model': activation: &id001 !!python/tuple
- true
- true
- true
bias: false
dropout: 0.1
emb_dim: 64
ff_dim: 128
flash: true
layer_norm: true
mlp: *id001
mlp_bias: true
num_heads: !!python/tuple
- 1
- 1
- 1
num_layers: 3
pos_enc: rotary
pos_max_len: 83
, 'training': eval_iter: 150
freeze_out: false
freeze_value: false
get_attn: 0
get_checkpoints: 500
identity_query: false
label_smoothing: 0
lr: 0.0005
optimizer: adamw
pad_ignore: true
schedule: triangle
total_steps: 60000
warmup_steps: 20000
weight_decay: 0.01
, 'wandb': project: Reasoning
}, '_locked': False, '_type_safe': True, '_convert_dict': True, '_allow_dotted_keys': False, '_sort_keys': True}
2025-04-08 20:34:16,450 INFO    MainThread:24616 [wandb_init.py:init():644] re-initializing run, found existing run on stack: j7gt3w11
2025-04-08 20:34:16,451 INFO    MainThread:24616 [wandb_run.py:_finish():2155] finishing run hyan84-university-of-wisconsin-madison/Reasoning/j7gt3w11
2025-04-08 20:34:16,452 INFO    MainThread:24616 [jupyter.py:save_history():459] not saving jupyter history
2025-04-08 20:34:16,452 INFO    MainThread:24616 [jupyter.py:save_ipynb():387] not saving jupyter notebook
2025-04-08 20:34:16,452 INFO    MainThread:24616 [wandb_init.py:_jupyter_teardown():461] cleaning up jupyter logic
2025-04-08 20:34:16,452 INFO    MainThread:24616 [wandb_run.py:_atexit_cleanup():2420] got exitcode: 0
2025-04-08 20:34:16,452 INFO    MainThread:24616 [wandb_run.py:_restore():2402] restore
2025-04-08 20:34:16,452 INFO    MainThread:24616 [wandb_run.py:_restore():2408] restore done
2025-04-08 20:34:37,616 WARNING MainThread:24616 [wandb_init.py:init():1260] interrupted
Traceback (most recent call last):
  File "C:\Users\Hao\anaconda3\envs\LLM\Lib\site-packages\wandb\sdk\wandb_init.py", line 1256, in init
    return wi.init()
           ^^^^^^^^^
  File "C:\Users\Hao\anaconda3\envs\LLM\Lib\site-packages\wandb\sdk\wandb_init.py", line 654, in init
    latest_run.finish()
  File "C:\Users\Hao\anaconda3\envs\LLM\Lib\site-packages\wandb\sdk\wandb_run.py", line 451, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hao\anaconda3\envs\LLM\Lib\site-packages\wandb\sdk\wandb_run.py", line 393, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hao\anaconda3\envs\LLM\Lib\site-packages\wandb\sdk\wandb_run.py", line 2149, in finish
    return self._finish(exit_code)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hao\anaconda3\envs\LLM\Lib\site-packages\wandb\sdk\wandb_run.py", line 2179, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "C:\Users\Hao\anaconda3\envs\LLM\Lib\site-packages\wandb\sdk\wandb_run.py", line 2432, in _atexit_cleanup
    self._on_finish()
  File "C:\Users\Hao\anaconda3\envs\LLM\Lib\site-packages\wandb\sdk\wandb_run.py", line 2681, in _on_finish
    _ = exit_handle.wait(
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\Hao\anaconda3\envs\LLM\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hao\anaconda3\envs\LLM\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hao\anaconda3\envs\LLM\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hao\anaconda3\envs\LLM\Lib\threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hao\anaconda3\envs\LLM\Lib\threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-04-08 20:34:42,970 WARNING MsgRouterThr:24616 [router.py:message_loop():75] message_loop has been closed
